# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  apipfx:
    container_name: apipfx
    build:
      context: .
      dockerfile: ApiPfx/Dockerfile
    image: apipfx
    ports:
      - 8075:8080