# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  apipfx:
    image: apipfx
    build:
      context: .
      dockerfile: ApiPfx/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8075:8075
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
